"""Recompute noise-experiment metrics from existing video artifacts.

This does not encode or preprocess anything. It scans an output directory for
artifacts generated by ``run_noise_experiment.py`` and rebuilds raw/summary CSVs
using the local metric implementation.
"""

from __future__ import annotations

import argparse
import os
import re
from collections import defaultdict

from dtcwt_video.evaluate_metrics import evaluate_video_quality
from dtcwt_video.experiment_analysis import get_actual_bitrate_kbps
from scripts.run_noise_experiment import (
    ALL_BASELINES,
    METRIC_NAMES,
    PRECODEC_METHODS,
    _append_result_row,
    _metrics_to_dict,
    compute_condition_summary,
    plot_bd_rate_comparison,
    plot_codec_gain_heatmap,
    plot_condition_rd_curves,
    plot_delta_psnr_trend,
    plot_overlay_rd_curves,
    plot_pre_post_delta_bars,
    save_condition_csv,
    save_reliable_metrics_csv,
    save_summary_csv,
)


POST_RE = re.compile(
    r"(?P<video>.+)_s(?P<sigma>-?\d+)_(?P<method>base|nr|hqdn3d|dwt|gaussian|prop)_(?P<br>\d+)k\.mp4$"
)
PRE_RE = re.compile(
    r"(?P<video>.+)_s(?P<sigma>-?\d+)_(?P<method>noisy|hqdn3d|dwt|gaussian|prop)\.y4m$"
)
METHOD_ORDER = ["base", "nr", "hqdn3d", "dwt", "gaussian", "prop"]


def _empty_condition(video: str, sigma: int) -> dict:
    return {
        "video": video,
        "sigma": sigma,
        "bitrates": [],
        "active_methods": [],
        "actual_bitrates": {},
        "rows": [],
        "pre_metrics": {},
        "preprocessed_paths": {},
        "artifacts": [],
    }


def _ensure_method(results: dict, method: str) -> None:
    if method not in results["active_methods"] and method in ALL_BASELINES:
        results["active_methods"].append(method)
        results["active_methods"].sort(key=lambda m: METHOD_ORDER.index(m))
    results.setdefault("actual_bitrates", {}).setdefault(method, [])
    if method in ALL_BASELINES and method not in results:
        results[method] = {metric: [] for metric in METRIC_NAMES}


def _scan_artifacts(output_dir: str) -> tuple[dict, dict]:
    post = defaultdict(dict)
    pre = defaultdict(dict)

    for root, _, files in os.walk(output_dir):
        for name in files:
            post_match = POST_RE.match(name)
            if post_match:
                video = post_match.group("video")
                sigma = int(post_match.group("sigma"))
                method = post_match.group("method")
                bitrate = int(post_match.group("br"))
                post[(video, sigma)][(method, bitrate)] = os.path.join(root, name)
                continue

            pre_match = PRE_RE.match(name)
            if pre_match:
                video = pre_match.group("video")
                sigma = int(pre_match.group("sigma"))
                method = pre_match.group("method")
                pre[(video, sigma)][method] = os.path.join(root, name)

    return post, pre


def _build_condition(video: str, sigma: int, post_files: dict, pre_files: dict,
                     input_dir: str, num_frames: int) -> dict | None:
    clean_video = os.path.join(input_dir, f"{video}.y4m")
    if not os.path.exists(clean_video):
        print(f"  [Skip] 참조 영상 없음: {clean_video}")
        return None

    results = _empty_condition(video, sigma)

    for method in PRECODEC_METHODS:
        path = pre_files.get(method)
        if not path:
            continue
        print(f"  [Pre 평가] {video} s{sigma} {method}")
        metric_tuple = evaluate_video_quality(clean_video, path, num_frames_custom=num_frames)
        metrics = _metrics_to_dict(metric_tuple)
        results["pre_metrics"][method] = metrics
        results["preprocessed_paths"][method] = path
        results["artifacts"].append(path)
        _append_result_row(
            results["rows"],
            video=video,
            sigma=sigma,
            seed="",
            stage="pre_x264",
            method=method,
            target_bitrate_kbps="",
            actual_bitrate_kbps="",
            metrics=metrics,
        )

    bitrates = sorted({bitrate for _, bitrate in post_files})
    results["bitrates"] = bitrates

    for method in METHOD_ORDER:
        method_items = [
            (bitrate, path)
            for (m, bitrate), path in post_files.items()
            if m == method
        ]
        if not method_items:
            continue
        _ensure_method(results, method)
        for bitrate, path in sorted(method_items):
            print(f"  [Post 평가] {video} s{sigma} {method} {bitrate}k")
            metric_tuple = evaluate_video_quality(clean_video, path, num_frames_custom=num_frames)
            metrics = _metrics_to_dict(metric_tuple)
            actual_bitrate = get_actual_bitrate_kbps(path)
            results["actual_bitrates"][method].append(actual_bitrate)
            results["artifacts"].append(path)
            for i, name in enumerate(METRIC_NAMES):
                results[method][name].append(metric_tuple[i])
            _append_result_row(
                results["rows"],
                video=video,
                sigma=sigma,
                seed="",
                stage="post_x264",
                method=method,
                target_bitrate_kbps=bitrate,
                actual_bitrate_kbps=actual_bitrate,
                metrics=metrics,
            )

    return results


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Recompute raw/summary metrics from existing noise-experiment artifacts."
    )
    parser.add_argument("-i", "--input_dir", default="videos",
                        help="Directory containing clean reference .y4m files.")
    parser.add_argument("-o", "--output_dir", default="outputs/noise_experiment",
                        help="Directory containing server-generated artifacts.")
    parser.add_argument("--num_frames", type=int, default=60,
                        help="Number of frames for OpenCV-based custom metrics.")
    parser.add_argument("--plots", action="store_true",
                        help="Also redraw plots after recomputing CSVs.")
    args = parser.parse_args()

    output_dir = os.path.abspath(args.output_dir)
    input_dir = os.path.abspath(args.input_dir)
    post_by_condition, pre_by_condition = _scan_artifacts(output_dir)
    conditions = sorted(set(post_by_condition) | set(pre_by_condition))
    if not conditions:
        raise SystemExit(f"No matching .mp4/.y4m artifacts found in {output_dir}")

    all_results = {}
    all_summaries = {}

    for video, sigma in conditions:
        print(f"\n=== {video} s{sigma} 지표 재계산 ===")
        results = _build_condition(
            video, sigma,
            post_by_condition.get((video, sigma), {}),
            pre_by_condition.get((video, sigma), {}),
            input_dir,
            args.num_frames,
        )
        if results is None:
            continue
        save_condition_csv(results, output_dir)
        all_results.setdefault(video, {})[sigma] = results

        if "base" in results and results.get("bitrates"):
            summary = compute_condition_summary(results)
            all_summaries.setdefault(video, {})[sigma] = summary
            if args.plots:
                plot_condition_rd_curves(results, summary, output_dir)

    if all_summaries:
        save_summary_csv(all_summaries, output_dir)
        save_reliable_metrics_csv(all_summaries, output_dir)
        if args.plots:
            plot_overlay_rd_curves(all_results, output_dir)
            plot_bd_rate_comparison(all_summaries, output_dir)
            plot_delta_psnr_trend(all_results, output_dir)
            plot_pre_post_delta_bars(all_summaries, output_dir)
            plot_codec_gain_heatmap(all_summaries, output_dir)
    else:
        print("\nPost-x264 baseline 결과가 없어 summary CSV는 생성하지 않았습니다.")

    print(f"\n완료: {output_dir}")


if __name__ == "__main__":
    main()
